server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://39.104.159.18:3306/spring
    dbcp2:
      max-total: 5
      min-idle: 2
      max-idle: 2
  devtools:
    restart:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: dept8002
    prefer-ip-address: true

info:
  app: lichao123